# https://www.dabbleofdevops.com/blog/setup-a-redis-python-docker-dev-stack
version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379
    networks:
      - app-tier

  pose_parser_api:
    build:
      context: ./pose_parser
      dockerfile: Dockerfile
    ports:
      - "3080:5000"
    depends_on:
      - redis
    networks:
      - app-tier
    command:
      tail -f python api/app.py
  
  web_ui:
    build:
      context: ./web_ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./web-ui:/usr/src/app/my-app
      - ./web-ui/node_modules:/usr/src/app/my-app/node_modules

networks:
  app-tier:
    driver: bridge